// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// cd common/idl; protoc -I message  --go_out=plugins=grpc:message  message/message.proto
type CmdType int32

const (
	CmdType_Login     CmdType = 0
	CmdType_Heartbeat CmdType = 1
	CmdType_ReConn    CmdType = 2
	CmdType_ACK       CmdType = 3
)

var CmdType_name = map[int32]string{
	0: "Login",
	1: "Heartbeat",
	2: "ReConn",
	3: "ACK",
}

var CmdType_value = map[string]int32{
	"Login":     0,
	"Heartbeat": 1,
	"ReConn":    2,
	"ACK":       3,
}

func (x CmdType) String() string {
	return proto.EnumName(CmdType_name, int32(x))
}

func (CmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

// 顶层cmd pb结构
type MsgCmd struct {
	Type                 CmdType  `protobuf:"varint,1,opt,name=Type,proto3,enum=message.CmdType" json:"Type,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCmd) Reset()         { *m = MsgCmd{} }
func (m *MsgCmd) String() string { return proto.CompactTextString(m) }
func (*MsgCmd) ProtoMessage()    {}
func (*MsgCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MsgCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCmd.Unmarshal(m, b)
}
func (m *MsgCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCmd.Marshal(b, m, deterministic)
}
func (m *MsgCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCmd.Merge(m, src)
}
func (m *MsgCmd) XXX_Size() int {
	return xxx_messageInfo_MsgCmd.Size(m)
}
func (m *MsgCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCmd.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCmd proto.InternalMessageInfo

func (m *MsgCmd) GetType() CmdType {
	if m != nil {
		return m.Type
	}
	return CmdType_Login
}

func (m *MsgCmd) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// ACK 消息
type ACKMsg struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Type                 CmdType  `protobuf:"varint,3,opt,name=Type,proto3,enum=message.CmdType" json:"Type,omitempty"`
	ConnID               uint64   `protobuf:"varint,4,opt,name=ConnID,proto3" json:"ConnID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACKMsg) Reset()         { *m = ACKMsg{} }
func (m *ACKMsg) String() string { return proto.CompactTextString(m) }
func (*ACKMsg) ProtoMessage()    {}
func (*ACKMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *ACKMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACKMsg.Unmarshal(m, b)
}
func (m *ACKMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACKMsg.Marshal(b, m, deterministic)
}
func (m *ACKMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACKMsg.Merge(m, src)
}
func (m *ACKMsg) XXX_Size() int {
	return xxx_messageInfo_ACKMsg.Size(m)
}
func (m *ACKMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ACKMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ACKMsg proto.InternalMessageInfo

func (m *ACKMsg) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ACKMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ACKMsg) GetType() CmdType {
	if m != nil {
		return m.Type
	}
	return CmdType_Login
}

func (m *ACKMsg) GetConnID() uint64 {
	if m != nil {
		return m.ConnID
	}
	return 0
}

// 登陆消息
type LoginMsgHead struct {
	DeviceID             uint64   `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsgHead) Reset()         { *m = LoginMsgHead{} }
func (m *LoginMsgHead) String() string { return proto.CompactTextString(m) }
func (*LoginMsgHead) ProtoMessage()    {}
func (*LoginMsgHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *LoginMsgHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsgHead.Unmarshal(m, b)
}
func (m *LoginMsgHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsgHead.Marshal(b, m, deterministic)
}
func (m *LoginMsgHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsgHead.Merge(m, src)
}
func (m *LoginMsgHead) XXX_Size() int {
	return xxx_messageInfo_LoginMsgHead.Size(m)
}
func (m *LoginMsgHead) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsgHead.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsgHead proto.InternalMessageInfo

func (m *LoginMsgHead) GetDeviceID() uint64 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type LoginMsg struct {
	Head                 *LoginMsgHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	LoginMsgBody         []byte        `protobuf:"bytes,2,opt,name=LoginMsgBody,proto3" json:"LoginMsgBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginMsg) Reset()         { *m = LoginMsg{} }
func (m *LoginMsg) String() string { return proto.CompactTextString(m) }
func (*LoginMsg) ProtoMessage()    {}
func (*LoginMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *LoginMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg.Unmarshal(m, b)
}
func (m *LoginMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg.Marshal(b, m, deterministic)
}
func (m *LoginMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg.Merge(m, src)
}
func (m *LoginMsg) XXX_Size() int {
	return xxx_messageInfo_LoginMsg.Size(m)
}
func (m *LoginMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg proto.InternalMessageInfo

func (m *LoginMsg) GetHead() *LoginMsgHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *LoginMsg) GetLoginMsgBody() []byte {
	if m != nil {
		return m.LoginMsgBody
	}
	return nil
}

// 心跳消息
type HeartbeatMsgHead struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatMsgHead) Reset()         { *m = HeartbeatMsgHead{} }
func (m *HeartbeatMsgHead) String() string { return proto.CompactTextString(m) }
func (*HeartbeatMsgHead) ProtoMessage()    {}
func (*HeartbeatMsgHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *HeartbeatMsgHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatMsgHead.Unmarshal(m, b)
}
func (m *HeartbeatMsgHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatMsgHead.Marshal(b, m, deterministic)
}
func (m *HeartbeatMsgHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatMsgHead.Merge(m, src)
}
func (m *HeartbeatMsgHead) XXX_Size() int {
	return xxx_messageInfo_HeartbeatMsgHead.Size(m)
}
func (m *HeartbeatMsgHead) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatMsgHead.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatMsgHead proto.InternalMessageInfo

type HeartbeatMsg struct {
	Head                 *HeartbeatMsgHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	HeartbeatMsgBody     []byte            `protobuf:"bytes,2,opt,name=HeartbeatMsgBody,proto3" json:"HeartbeatMsgBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HeartbeatMsg) Reset()         { *m = HeartbeatMsg{} }
func (m *HeartbeatMsg) String() string { return proto.CompactTextString(m) }
func (*HeartbeatMsg) ProtoMessage()    {}
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *HeartbeatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatMsg.Unmarshal(m, b)
}
func (m *HeartbeatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatMsg.Marshal(b, m, deterministic)
}
func (m *HeartbeatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatMsg.Merge(m, src)
}
func (m *HeartbeatMsg) XXX_Size() int {
	return xxx_messageInfo_HeartbeatMsg.Size(m)
}
func (m *HeartbeatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatMsg proto.InternalMessageInfo

func (m *HeartbeatMsg) GetHead() *HeartbeatMsgHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *HeartbeatMsg) GetHeartbeatMsgBody() []byte {
	if m != nil {
		return m.HeartbeatMsgBody
	}
	return nil
}

// 重连消息
type ReConnMsgHead struct {
	ConnID               uint64   `protobuf:"varint,1,opt,name=ConnID,proto3" json:"ConnID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReConnMsgHead) Reset()         { *m = ReConnMsgHead{} }
func (m *ReConnMsgHead) String() string { return proto.CompactTextString(m) }
func (*ReConnMsgHead) ProtoMessage()    {}
func (*ReConnMsgHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *ReConnMsgHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReConnMsgHead.Unmarshal(m, b)
}
func (m *ReConnMsgHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReConnMsgHead.Marshal(b, m, deterministic)
}
func (m *ReConnMsgHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReConnMsgHead.Merge(m, src)
}
func (m *ReConnMsgHead) XXX_Size() int {
	return xxx_messageInfo_ReConnMsgHead.Size(m)
}
func (m *ReConnMsgHead) XXX_DiscardUnknown() {
	xxx_messageInfo_ReConnMsgHead.DiscardUnknown(m)
}

var xxx_messageInfo_ReConnMsgHead proto.InternalMessageInfo

func (m *ReConnMsgHead) GetConnID() uint64 {
	if m != nil {
		return m.ConnID
	}
	return 0
}

type ReConnMsg struct {
	Head                 *ReConnMsgHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ReConnMsgBody        []byte         `protobuf:"bytes,2,opt,name=ReConnMsgBody,proto3" json:"ReConnMsgBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReConnMsg) Reset()         { *m = ReConnMsg{} }
func (m *ReConnMsg) String() string { return proto.CompactTextString(m) }
func (*ReConnMsg) ProtoMessage()    {}
func (*ReConnMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *ReConnMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReConnMsg.Unmarshal(m, b)
}
func (m *ReConnMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReConnMsg.Marshal(b, m, deterministic)
}
func (m *ReConnMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReConnMsg.Merge(m, src)
}
func (m *ReConnMsg) XXX_Size() int {
	return xxx_messageInfo_ReConnMsg.Size(m)
}
func (m *ReConnMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ReConnMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ReConnMsg proto.InternalMessageInfo

func (m *ReConnMsg) GetHead() *ReConnMsgHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ReConnMsg) GetReConnMsgBody() []byte {
	if m != nil {
		return m.ReConnMsgBody
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.CmdType", CmdType_name, CmdType_value)
	proto.RegisterType((*MsgCmd)(nil), "message.MsgCmd")
	proto.RegisterType((*ACKMsg)(nil), "message.ACKMsg")
	proto.RegisterType((*LoginMsgHead)(nil), "message.LoginMsgHead")
	proto.RegisterType((*LoginMsg)(nil), "message.LoginMsg")
	proto.RegisterType((*HeartbeatMsgHead)(nil), "message.HeartbeatMsgHead")
	proto.RegisterType((*HeartbeatMsg)(nil), "message.HeartbeatMsg")
	proto.RegisterType((*ReConnMsgHead)(nil), "message.ReConnMsgHead")
	proto.RegisterType((*ReConnMsg)(nil), "message.ReConnMsg")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x13, 0x93, 0x66, 0x4c, 0x64, 0x19, 0xb0, 0x44, 0x4f, 0x65, 0x29, 0x58, 0x03,
	0x56, 0xa8, 0x17, 0xc1, 0x53, 0x9b, 0x1e, 0x5a, 0x6a, 0x40, 0x16, 0x2f, 0x0a, 0x1e, 0x52, 0xb3,
	0x84, 0x42, 0xdb, 0x2d, 0x4d, 0x11, 0xfa, 0xef, 0x25, 0xdb, 0xcd, 0x36, 0xab, 0xe0, 0x6d, 0x66,
	0x32, 0x6f, 0xbe, 0x97, 0x97, 0x40, 0xb8, 0xe6, 0x65, 0x99, 0x15, 0x7c, 0xb0, 0xdd, 0x89, 0xbd,
	0x40, 0x4f, 0xb5, 0x74, 0x0a, 0x6e, 0x5a, 0x16, 0xc9, 0x3a, 0xc7, 0x1e, 0x38, 0x6f, 0x87, 0x2d,
	0x8f, 0xac, 0xae, 0xd5, 0xbf, 0x1c, 0x92, 0x41, 0x2d, 0x48, 0xd6, 0x79, 0x35, 0x67, 0xf2, 0x29,
	0x46, 0xe0, 0xbd, 0x66, 0x87, 0x95, 0xc8, 0xf2, 0xa8, 0xd5, 0xb5, 0xfa, 0x01, 0xab, 0x5b, 0xba,
	0x02, 0x77, 0x94, 0xcc, 0xd3, 0xb2, 0x40, 0x04, 0x27, 0x11, 0xf9, 0xf1, 0x52, 0xc8, 0x64, 0x8d,
	0x04, 0xec, 0xb4, 0x2c, 0xa4, 0xc6, 0x67, 0x55, 0xa9, 0x79, 0xf6, 0xbf, 0xbc, 0x0e, 0xb8, 0x89,
	0xd8, 0x6c, 0x66, 0x93, 0xc8, 0xe9, 0x5a, 0x7d, 0x87, 0xa9, 0x8e, 0xc6, 0x10, 0xbc, 0x88, 0x62,
	0xb9, 0x49, 0xcb, 0x62, 0xca, 0xb3, 0x1c, 0x6f, 0xa0, 0x3d, 0xe1, 0xdf, 0xcb, 0x2f, 0x3e, 0x9b,
	0x48, 0xae, 0xc3, 0x74, 0x4f, 0xdf, 0xa1, 0x5d, 0xef, 0xe2, 0x1d, 0x38, 0xd5, 0xbe, 0xdc, 0xb9,
	0x18, 0x5e, 0x69, 0x6a, 0xf3, 0x18, 0x93, 0x2b, 0x48, 0x4f, 0x88, 0xb1, 0xc8, 0x0f, 0xea, 0x7d,
	0x8d, 0x19, 0x45, 0x20, 0x53, 0x9e, 0xed, 0xf6, 0x0b, 0x9e, 0xed, 0x95, 0x9a, 0x2e, 0x21, 0x68,
	0xce, 0xf0, 0xde, 0x40, 0x5e, 0x6b, 0xe4, 0x6f, 0xa1, 0xc2, 0xc6, 0xe6, 0xc9, 0x06, 0xfa, 0xcf,
	0x9c, 0xde, 0x42, 0xc8, 0x78, 0x95, 0x48, 0x1d, 0xc3, 0x29, 0x2e, 0xcb, 0x88, 0xeb, 0x13, 0x7c,
	0xbd, 0x88, 0xb1, 0x61, 0xa8, 0xa3, 0x0d, 0x19, 0xa7, 0x94, 0x9b, 0x5e, 0x83, 0xd0, 0xb0, 0x62,
	0x0e, 0xe3, 0x27, 0xf0, 0xd4, 0x67, 0x43, 0x1f, 0xce, 0x65, 0x42, 0xe4, 0x0c, 0x43, 0xf0, 0xb5,
	0x63, 0x62, 0x21, 0x80, 0x7b, 0x54, 0x91, 0x16, 0x7a, 0x60, 0x8f, 0x92, 0x39, 0xb1, 0xc7, 0xc1,
	0x07, 0x0c, 0x1e, 0x9e, 0x95, 0x83, 0x85, 0x2b, 0xff, 0xce, 0xc7, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x69, 0x92, 0xcf, 0x7d, 0xae, 0x02, 0x00, 0x00,
}
